name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e

          echo "Updating Docmost..."

          cd /opt/docmost/app

          echo "Creating backup before update..."
          /root/backup-docmost-strych.sh || echo "Warning: Backup failed, continuing..."

          echo "Fetching latest code from GitHub..."
          git fetch origin
          git reset --hard origin/main

          echo "Stopping old containers..."
          cd /opt/docmost
          docker compose down

          echo "Building new Docker image..."
          cd /opt/docmost/app
          docker build -t docmost-btc:latest .

          echo "Starting new containers..."
          cd /opt/docmost
          docker compose up -d

          sleep 15

          echo "Container status:"
          docker compose ps

          echo "Deployment completed!"
          echo "Check: https://wiki.beyondthecloud.dev"