name: Build and Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docmost:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_OPTIONS=--max-old-space-size=4096

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        command_timeout: 15m
        script: |
          set -e

          echo "Updating Docmost..."

          cd /opt/docmost

          echo "Pulling new image from Docker Hub..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/docmost:latest

          echo "Stopping old containers..."
          docker compose down

          echo "Starting new containers..."
          docker compose up -d

          sleep 15

          echo "Container status:"
          docker compose ps

          echo "Deployment completed!"
          echo "Check: https://wiki.beyondthecloud.dev"